# Generated by Django 4.1.2 on 2022-10-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_nome_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentário'),
        ),
    ]
